### ISSUE TITLE
[BUG] "Link to Dashboard" doesn't appear on either calculator

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#10]
**Actual Behavior**
There was no link to "choose different calculator" found on the Destination Page for theSpecialty and Commodity Crop Calculators.

**Expected behavior**
When opening the Destination Page for Specialty and Commodity Crop Calculators, I expected to see a link to return to the dashboard labelled "choose different calculator".

**To Reproduce**
On the Dashboard under "Choose Calculator" - select "Commodity Crop Pests" - select "Go to Calculator" - the link labelled "choose different calculator" should be absent. Repeat for "Specialty Crop Pests".

**Browser and Version**
Google Chrome, Version86.0.4240.183

**Platform**
Intel Desktop, Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/67065386/100016161-9c949d00-2d9e-11eb-95ea-59f984594d9f.png)

**Comment by odomaf** [comment]
Updated so there are three links at the top and bottom of each results page: Return to Dashboard, Calculate new commodity pest, calculate new specialty pest. 
![image](https://user-images.githubusercontent.com/67065386/102137841-10b3e500-3e21-11eb-8b88-45b708d4963b.png)

**Comment by Hwenner2010** [comment]
"Calculate Another" now appears and is a functional Link to Dashboard tool.
