### ISSUE TITLE
[BUG] Grape Berry Moth missing context data

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#19]
**Actual Behavior**
When viewing the grape berry moth page, the context table for generational expectations is missing from the bottom left of the screen

**Expected behavior**
When viewing the grape berry moth page, it's expected that there will be a table for generational expectations on the bottom left of the screen

**To Reproduce**
1. Go to dashboard page
2. Choose specialty calculator
3. On calculator page, select any station from the station drop down and "Grape Berry Moth" from the pest drop down.
4. Click Calculate
4. See that there is no table with generational data on the bottom left.

**Browser and Version**
Firefox - most current version

**Platform**
Windows 10 Dell Laptop

**Screenshots**
![image](https://user-images.githubusercontent.com/67065386/102245756-8d979b00-3ec3-11eb-8ab9-271d3f1ca26b.png)

**Comment by odomaf** [comment]
Waiting on Jennie/Kelly for data to put in the database

**Comment by odomaf** [comment]
Per Jennie and Kelly, the following data could be used in an emergency, but more accurate data will be available by the 5th (maybe):

810 DDs – egg laying first generation

1620 DDs – egg laying second generation

2430 DDs – egg laying third generation

**Comment by odomaf** [comment]
Pinged Jennie and Kelly for update about data that may be available for GBM now.

**Comment by odomaf** [comment]
The above info is correct, but biofix should be user enterable as "Wild grape bloom date"

**Comment by Hwenner2010** [comment]
Data Context Table appears alongside the graph for all sites. Issue appears to be resolved.
