### ISSUE TITLE
[BUG] Spotted Wing Drosophilaunder results missing information

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#3]
**Actual Behavior**
Under the "Specialty Crop Calculator" for ALL stations, the Data Context table and species image did not appear for the Spotted Wing Drosophila.

**Expected behavior**
Under "Specialty Crop Calculator" for ALL stations, when displaying data for the Spotted Wing Drosophila, a Data Context table and species image was expected to appear on the left side.

**To Reproduce**
On the Dashboard under "Choose Calculator" - select "Specialty Crop Pests" - select "Go to Calculator" - Select any station - select Spotted Wing Drosophila under "Select Pest" - "Calculate" - the table and species image should be absent on the left.

**Browser and Version**
 Google Chrome, Version86.0.4240.183

**Platform**
Intel Desktop, Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/67065386/100004308-ed9b9580-2d8c-11eb-8345-6b290f67fb54.png)

**Comment by odomaf** [comment]
SWD information not in database. It is a new pest, so the lifecycle context data isn't in the old calculator either. Sent email to Jennie and Kelly; waiting for response.

**Comment by odomaf** [comment]
Per Jennie, add this information to the database (each line is a new generation for a total of 5 generations):

260 DD  -- First egg laying by overwintered females 

510 DD – Emergence of adults begins

565 DD – egg laying by newly emerged adults begins

750 DD – peak emergence of adults

995 DD – peak egg laying

**Comment by odomaf** [comment]
When re-testing, please verify that all data in context table matches Jennie's notes above.

**Comment by Hwenner2010** [comment]
All parameters have been met and the calculator for Spotted Wing Drosophilaunder appears to be functioning properly
