### ISSUE TITLE
[BUG] Grape Berry Moth produces runtime error

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#4]
**Actual Behavior**
Under the "Specialty Crop Calculator" for ALL stations, calculating for the Grape Berry Moth produces an error page.

**Expected behavior**
Under "Specialty Crop Calculator" for ALL stations, data is expected when calculating for the Grape Berry Moth.

**To Reproduce**
On the Dashboard under "Choose Calculator" - select "Specialty Crop Pests" - select "Go to Calculator" - Under the "choose pest" dropdown menu select Grape Berry Moth - select any station - an error page appears when selecting "calculate"

**Browser and Version**
 Google Chrome, Version86.0.4240.183

**Platform**
Intel Desktop, Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/67065386/100004825-a95cc500-2d8d-11eb-94bb-a245b4d3256c.png)

**Comment by odomaf** [comment]
Running in dev mode shows that GBM has no IBASE47 column in the icddnhist table. Because no history can be grabbed, the whole thing is crashing. Emailed Jennie asking for guidance.

**Comment by odomaf** [comment]
Per Jennie - because pest is new, we do not have historical data, and she does not have time to put it together. Instead, instructions are to omit the historical line altogether for Grape Berry Moth.

**Comment by odomaf** [comment]
This problem is fixed, but it uncovered a new problem with missing data for Grape Berry Moth. I am making a new issue for the missing data. This bug can be closed when it is confirmed the crash is no longer occurring for this pest.

**Comment by Hwenner2010** [comment]
Grape Berry Moth was checked for every station and no longer produces a runtime error in the Specialty Crop Calculator. This issue appears to be resolved.
