### ISSUE TITLE
[BUG] Fruit tree leafroller missing context table for all stations

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#5]
**Actual Behavior**
Under the "Specialty Crop Calculator" for ALL stations, the Data Context table did not appear for the Fruit Tree Leafroller.

**Expected behavior**
Under "Specialty Crop Calculator" for ALL stations, when displaying data for the Fruit Tree Leafroller, a Data Context table was expected to appear at the bottom left.

**To Reproduce**
On the Dashboard under "Choose Calculator" - select "Specialty Crop Pests" - select "Go to Calculator" - Select any station - select Fruit Tree Leafroller under "Select Pest" - "Calculate" - the table should be absent at the bottom left.

**Browser and Version**
Google Chrome, Version86.0.4240.183

**Platform**
Intel Desktop, Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/67065386/100014322-d31ce880-2d9b-11eb-8fb9-58d71f696354.png)

**Comment by odomaf** [comment]
Fruit tree leafroller information was missing from database. It has been added and should now appear for all stations.

**Comment by Hwenner2010** [comment]
Data Context Table for the Fruit Tree Leafroller is now displayed for all stations. The issue appears to have been resolved.
