### ISSUE TITLE
[BUG] "Japanese Moth" should be "Japanese Beetle"

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#6]
Spinoff of issue regarding Japanese moth not being in specialty crop calculator -- tester reported Japanese Moth should be Japanese Beetle. Double check with Jennie and Kelly.

**Comment by odomaf** [comment]
Closed - this was a problem with the testing instructions not the code. The Japanese Beetle should not be in the specialty crop calculator, because it is only displayed as a seasonal map.

**Comment by Hwenner2010** [comment]
Japanese Beetle appears as a Seasonal Map and does not appear in either calculator. All appears to be functioning normally.
