### ISSUE TITLE
[BUG] Japanese Moth missing from Specialty Crop Calculator

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#7]
**Actual Behavior**
Under the "Specialty Crop Calculator" theJapanese Mothwas not an option in the "Choose Pest" dropdown menu.

**Expected behavior**
Under "Specialty Crop Calculator" when opening the "Choose Pest" dropdown menu, I expected to see theJapanese Mothas an option.

**To Reproduce**
On the Dashboard under "Choose Calculator" - select "Specialty Crop Pests" - select "Go to Calculator" - Under the "choose pest" dropdown menu, theJapanese Mothis not listed.

**Browser and Version**
Google Chrome, Version86.0.4240.183

**Platform**
Intel Desktop, Windows 10

**Comment by odomaf** [comment]
Ready for confirmation - problem was with test instructions not code, Japanese Beetle should not appear in any drop-downs because it is displayed via map directly from dashboard.

**Comment by Hwenner2010** [comment]
The Brown Marmorated Stinkbug appears only as a Seasonal Map, as it should. The issue appears to be resolved.
