### ISSUE TITLE
[BUG] Corn Beetle missing from specialty crop calculator

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#8]
**Actual Behavior**
Under the "Specialty Crop Calculator" theCorn Beetlewas not an option in the "Choose Pest" dropdown menu.

**Expected behavior**
Under "Specialty Crop Calculator" when opening the "Choose Pest" dropdown menu, I expected to see theCorn Beetleas an option.

**To Reproduce**
On the Dashboard under "Choose Calculator" - select "Specialty Crop Pests" - select "Go to Calculator" - Under the "choose pest" dropdown menu, theCorn Beetleis not listed.

**Browser and Version**
Google Chrome, Version86.0.4240.183

**Platform**
Intel Desktop, Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/67065386/100015128-13309b00-2d9d-11eb-8104-fcb6bd0fae1b.png)

**Comment by odomaf** [comment]
Ready for confirmation - problem was with testing instructions, not code. Corn Flea Beetle should not appear in drop-down, because it is displayed as a map from the dashboard.

**Comment by Hwenner2010** [comment]
Corn Flea Beetle appears only as a Seasonal Map, as it should. The issue appears to be resolved.
