### ISSUE TITLE
[BUG] Brown Marmorated Stinkbug missing from Specialty Crop Calculator

### ISSUE THREAD

**Issue by odomaf** [PRI-Illinois/WARM-PDD#9]
**Actual Behavior**
Under the "Specialty Crop Calculator" the Brown Marmorated Stinkbug was not an option in the "Choose Pest" dropdown menu.

**Expected behavior**
Under "Specialty Crop Calculator" when opening the "Choose Pest" dropdown menu, I expected to see the Brown Marmorated Stinkbug as an option.

**To Reproduce**
On the Dashboard under "Choose Calculator" - select "Specialty Crop Pests" - select "Go to Calculator" - Under the "choose pest" dropdown menu, the Brown Marmorated Stinkbugis not listed.

**Browser and Version**
Google Chrome, Version86.0.4240.183

**Platform**
Intel Desktop, Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/67065386/100015621-e3ce5e00-2d9d-11eb-92bd-6ab9640208cd.png)

**Comment by odomaf** [comment]
Read for tester confirmation - this was a problem with the testing instructions not the code. The Japanese Beetle should not be in the specialty crop calculator, because it is only displayed as a seasonal map.

**Comment by Hwenner2010** [comment]
Brown Marmorated Stinkbug does not appear under the Specialty Crop Calculator and does appear as an option for a Seasonal Map. All appears to be normal.
